### ISSUE TITLE
Add arm64 support to the docker image

### ISSUE THREAD

**Issue by peterstace** [wolandark/bash-dungeon#2]
```
$ docker pull wolandark/bash-dungeon
docker run -it wolandark/bash-dungeon
Using default tag: latest
latest: Pulling from wolandark/bash-dungeon
7bb465c29149: Pull complete
4347cddc5757: Pull complete
1d005d81d9c4: Pull complete
Digest: sha256:a00ce9bebd729cef1654a8c948ef0f8ac99c4a7ae3482407f0dd48b9954902aa
Status: Downloaded newer image for wolandark/bash-dungeon:latest
docker.io/wolandark/bash-dungeon:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/bin/bash: exec format error
```

**Comment by prochac** [comment]
> ```
> $ docker pull wolandark/bash-dungeon
> docker run -it wolandark/bash-dungeon
> Using default tag: latest
> latest: Pulling from wolandark/bash-dungeon
> 7bb465c29149: Pull complete
> 4347cddc5757: Pull complete
> 1d005d81d9c4: Pull complete
> Digest: sha256:a00ce9bebd729cef1654a8c948ef0f8ac99c4a7ae3482407f0dd48b9954902aa
> Status: Downloaded newer image for wolandark/bash-dungeon:latest
> docker.io/wolandark/bash-dungeon:latest
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> exec /usr/bin/bash: exec format error
> ```

`--platform linux/amd64` should help, doesn't it?

**Comment by wolandark** [comment]
This is not planned. I would accept a PR though.

**Comment by peterstace** [comment]
> `--platform linux/amd64` should help, doesn't it?

Unfortunately not, because my platform is arm64.

```
$ docker run -it wolandark/bash-dungeon --platform linux/amd64
docker run -it --platform linux/amd64 wolandark/bash-dungeon
exec /usr/bin/bash: exec format error
```

**Comment by wolandark** [comment]
FYI the docker image in nothing but a plain debian with this repo auto cloned, and cd-ed into. So if you can pull any debian/ubuntu image on your arm devices, you can then simply clone the repo.

Hope that helps.

**Comment by peterstace** [comment]
That's very helpful, thanks!
